global:
  owner: immarktube
  authToken: ${GITHUB_TOKEN}
  apiBaseURL: https://api.github.com
  gitBaseURL: https://github.com
  concurrency: 5
  noHook: true

repositories:
  - path: kubernetesDemo
  - path: careeranalyse-web
  - path: readList

hook:
  pre: echo "Running pre hook"
  post: echo "Running post hook"
